### ISSUE TITLE
RconSocket can find

### ISSUE THREAD

**Issue by Kacak41** [stefanodriussi/rconsharp#1]
when i tried 

INetworkSocket socket = new RconSocket();

Visual studio draw RconSocket red.

and asking :) create object

**Comment by Kacak41** [comment]
When i installed PM> Install-Package RconSharp.Socket it's now clear

**Comment by stefanodriussi** [comment]
Hi, i'm glad you've found the solution :)
Sorry for not making it more clear that the actual implementation is inside a separate package. I reopen the issue so i remember to  updatethe readme.

**Comment by Kacak41** [comment]
:) i am trying to make a rcon client with telegram ,if i finish it i will publish to everyone :)

**Comment by stefanodriussi** [comment]
Nice! If you need any help just tell me

**Comment by stefanodriussi** [comment]
#4 Updated the documentation
