### ISSUE TITLE
genural noob alert (and hes issues)

### ISSUE THREAD

**Issue by noahthegame0** [stefanodriussi/rconsharp#10]
1. qestion is while trying to use the exable i got the following error:
socketexception an existing connection was forcibly closed by the remote host
why is this?

2. qestion the first arument of ConnectAsync should be the ip of the rcon server right?

i have no idea if the devoeloper still looks at these issues?
if you do that whould be great

**Comment by noahthegame0** [comment]
aaaaa wait am not closeing the connection is that it? if it is then i still have the last qestion

**Comment by noahthegame0** [comment]
maybe not... still need help!

**Comment by stefanodriussi** [comment]
Hi there @noahthegame0 
I've recently decided to start working again on this project! Right now I'm working on a general refactoring in order to convert the library to .net Standard and get rid of the PCL + specific implementation packages.
I'll try to look into this matter as soon as I can. In the mean time, could you please tell me what kind of RCON server are you connecting to ? Is RCON properly configured with the password and the port is opened ?

Regarding your questions
1) Are you sure you're connecting to the correct server/port ?
2) Correct, the first parameter is the ip address of the remote server

Cheers

**Comment by noahthegame0** [comment]
thanks for answering my qestion so fast:

the rcon "server" is running and working on a sniper elite 4 server
i have a rcon admin console for the server and rcon does work
if it helps at all this rcon client works to the server: http://snipereliteadmin.com/#!/ (but i know that may not help you)

1. i think so am going to redo the project

**Comment by noahthegame0** [comment]
`static void Main(string[] args)
        {
            //Login();
            
            TestAsync();
            Thread.Sleep(100000);
        }

        static async Task TestAsync()
        {

            Console.Clear();
            Console.WriteLine("connecting...");
            // Connect to a server
            // create an instance of the socket. In this case i've used the .Net 4.5 object defined in the project
            INetworkSocket socket = new RconSocket();

            // create the RconMessenger instance and inject the socket
            RconMessenger messenger = new RconMessenger(socket);

            // initiate the connection with the remote server
            bool isConnected = await messenger.ConnectAsync("108.61.112.29", 22020);

            // try to authenticate with your supersecretpassword (... obviously this is my hackerproof key, you shoul use yours)
            Console.WriteLine("authenticateing...");
            bool authenticated = await messenger.AuthenticateAsync("1393023");
            Console.WriteLine("checking bool...");
            if (authenticated)
            {

                // if we fall here, we're good to go! from this point on the connection is authenticated and you can send commands 
                // to the server
                Console.WriteLine(await messenger.ExecuteCommandAsync("/help"));
            } else
            {
                Console.WriteLine("not authenticated");
            }
        }`


again the text "checking bold..." nerver gets writen the AuthenticateAsync method puts the code into a loop

your libary does connect to the rcon server as my rconadmin client reports a rcon connection evrey time i run my project
