### ISSUE TITLE
System.ArgumentOutOfRangeException when authenticating

### ISSUE THREAD

**Issue by GenericName48** [stefanodriussi/rconsharp#11]
I'm not sure if this repo is still active, but I came across it and it seems perfect for what I want to do, I am getting the following error when trying to do the code below.
Error:
`Unhandled Exception: System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
Parameter name: bytes
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at RconSharp.RconPacket.FromBytes(Byte[] buffer)
   at RconSharp.RconMessenger.<AuthenticateAsync>d__3.MoveNext()`

Code:
```// create an instance of the socket. In this case i've used the .Net 4.5 object defined in the project
INetworkSocket socket = new RconSocket();

// create the RconMessenger instance and inject the socket
RconMessenger messenger = new RconMessenger(socket);

// initiate the connection with the remote server
bool isConnected = await messenger.ConnectAsync("IP_HERE", 27115);

// try to authenticate with your supersecretpassword (... obviously this is my hackerproof key, you shoul use yours)
bool authenticated = await messenger.AuthenticateAsync("PASSWORD_HERE");
if (authenticated)
{
    // if we fall here, we're good to go! from this point on the connection is authenticated and you can send commands 
    // to the server
    var response = await messenger.ExecuteCommandAsync("/broadcast This is a test.");
    Console.WriteLine(response);
}

**Comment by stefanodriussi** [comment]
Hi @GenericName48  (now this sounds strange ...) anyways, I'm trying to find some time to update this repo, at least convert it to a .netstandard package and get rid of the old stuff.
Regarding your issue, could you please tell me what kind of server/game are you connecting to ?
When this library was implemented, I used Minecraft as a target but then I discovered that there are some slight differences in how other servers/games answer to the Authenticate call.

**Comment by GenericName48** [comment]
Hi, sorry for the late response @stefanodriussi. The game I am using is called [Unturned ](https://store.steampowered.com/app/304930) and is on Steam. RCON support is added via a Server-Module called [RocketMod](https://rocketmod.net/). I am using RocketMod version 4, and the GitHub link to that is [here](https://github.com/RocketMod/Rocket.Unturned/tree/legacy).

Thanks for replying and looking into this.
