### ISSUE TITLE
System.ArgumentException | Can't insert more than 2 values

### ISSUE THREAD

**Issue by TempnameVulla** [stefanodriussi/rconsharp#17]
This happens when I try to run a command that has more than 2 values.

It works: sendmessage test
Not working: sendmessage test 22882

code:
```
RconMessenger messenger = new RconMessenger(new RconSocket());

messenger.ConnectAsync("ip", 27015);
messenger.AuthenticateAsync("pwd")

await messenger.ExecuteCommandAsync("sendmessage test"); //OK bro, no problem.
await messenger.ExecuteCommandAsync("sendmessage test 22882"); //and whoops error
```

error:
`System.ArgumentException: "Destination array was not long enough. Check destIndex and length, and the array's lower bounds."`

**Comment by stefanodriussi** [comment]
I'll look into it. I'm in the middle of a complete rewrite of this library and hopefully things like this will be fixed for good.
Sorry about that
