### ISSUE TITLE
command send

### ISSUE THREAD

**Issue by sysworx** [stefanodriussi/rconsharp#2]
var response = messenger.ExecuteCommandAsync("/help");

how can i get the output from this command?

**Comment by stefanodriussi** [comment]
Hi,
sorry about this issue ! It's an error in the documentation. I will correct it straight away.
The `ExecuteCommandAsync `method is marked as `async `and returns a `Task<string>` . In order to get the string representation of the server response you have two ways:
`var response = await messenger.ExecuteCommandAsync("/help");`
(notice che added `await `keyword) or 
`var response = messenger.ExecuteCommandAsync("/help").Result();`

**Comment by stefanodriussi** [comment]
#3

**Comment by sysworx** [comment]
if i try this and send /help i got "the server received but no response?

**Comment by stefanodriussi** [comment]
Are you sure the server is properly configured to listen

**Comment by sysworx** [comment]
The Server is an ARK Server, and if i try to send /help for example i get a help text in RCOn Clients, so i wonder why i dont get the help text here :)

**Comment by stefanodriussi** [comment]
Unfortunately I don't own ARK so I can't test it on his dedicated server. Could you please tell me some more details about the issue ? Have you authenticated the connection prior to sending the other commands ? That message you posted is a string returned as a response or an exception ?

**Comment by sysworx** [comment]
I think its a response... testet it on mcrcon there comes the same 
Am 03.06.2016 10:42 schrieb Stefano Driussi <notifications@github.com>:Unfortunately I don't own ARK so I can't test it on his dedicated server. Could you please tell me some more details about the issue ? Have you authenticated the connection prior to sending the other commands ? That message you posted is a string returned as a response or an exception ?

**Comment by stefanodriussi** [comment]
As soon as i have the chance I will try this with an ARK dedicated server and I'll let you know

**Comment by sysworx** [comment]
how you send chat messages in your exampe? Im not in C# and WPF ... i use it like this:

Dim restart10 As Object = messenger.ExecuteCommandAsync("AC: Update available, Server have to be restarted! Restart in 10 Minutes... ").Result

but this is a command no chat message...

**Comment by stefanodriussi** [comment]
Sorry for the late response.
First thing, are you sure that's the correct syntax for broadcasting a message in ARK ? Shouldn't it be something like ?
`/say AC: Update available, Server have to be restarted! Restart in 10 Minutes...`
