### ISSUE TITLE
No longer works in .NET Framework

### ISSUE THREAD

**Issue by wildyaboku** [stefanodriussi/rconsharp#32]
Hi @stefanodriussi,

Thanks for all your hard work on this. I've been following this package since early this year.

When you switched to netstandard 2.0, the package still worked fine with .NET Framework 4.6.1+. But netstandard 2.1 breaks compatibility with .NET Framework entirely, in fact Microsoft suggests packages remain on 2.0 for this reason unless they need the new features.

All the details here - https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-platforms-support and here - https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/

I'm just curious if breaking support for .NET Framework was intentional or by mistake?

**Comment by stefanodriussi** [comment]
Hi @wildyaboku ,
thanks for your interest in this project.
You're right, targeting netstandard 2.1 breaks compatibility with .NET Framework 4.6.1 . The reason why I decided to use that target was that I wanted to reimplement rconsharp using the new System.IO.Pipelines and the Span<T> type.
Would it be possible for your project to change target ? I'm open for suggestions and feel free to carry on with this conversation :)

**Comment by stefanodriussi** [comment]
@wildyaboku any thoughts on this ?

**Comment by wildyaboku** [comment]
Unfortunately the only wiggle room I had was to bump up to a newer .NET Framework version, so I was forced to use an alternate library in the short term, though we are planning a .NET Core rewrite in the future -- I'll make the switch back to rconsharp once that happens! :)

You can close this if you want, since there's not really a way to "fix" it other than rolling back.

**Comment by stefanodriussi** [comment]
Thanks for updating on the issue :) too bad you couldn't use it as is :/ but I'm glad you will consider rconsharp again in the future.
Good luck with your project and feel free to ping me here if you need additional help
