### ISSUE TITLE
Issue with ExecuteCommandAsync

### ISSUE THREAD

**Issue by Phoenigore** [stefanodriussi/rconsharp#5]
Hello, I have an issue with the ExecuteCommandAsync command.
I'm trying to send an "echo Test" command to my CSGO server.

If I do 
protected async Task<String> SendMessage(Server server, String message)
        {
            INetworkSocket socket = new RconSocket();
            RconMessenger messenger = new RconMessenger(socket);
            bool isConnected = await messenger.ConnectAsync(server.Address, server.Port);
            bool authenticated = await messenger.AuthenticateAsync(server.RconPassword);
            if (!authenticated)
            {
                return string.Empty;
            }
            Task<string> task = messenger.ExecuteCommandAsync(message);
            task.Wait();
            return task.Result;
        }

the result is always empty.
But, if I launch in debug mode with step by step mode, the result is not empty anymore.

I have the same issue with await syntax (String ret = await messenger.ExecuteCommandAsync(message);)

Could you help me ?

Regards.
Phoenigore.

**Comment by stefanodriussi** [comment]
Hi @Phoenigore ,
sure I will help you.
Is your CS:GO server properly configured for RCON ? setting the password in the config file should be sufficient.
That isConnected variable is set to true or false before the call to AuthenticateAsync ?
