### ISSUE TITLE
Minecraft newlines aren't transmitted properly

### ISSUE THREAD

**Issue by Foxite** [stefanodriussi/rconsharp#51]
If I run do this while connected to my minecraft server:

`string result = await rcon.ExecuteCommandAsync("banlist")`

The result will be something like:

`There are 2 bans:User was banned by Foxite_: griefingTest was banned by Foxite_: bla`

As opposed to

```
There are 2 bans:
User was banned by Foxite_: griefing
Test was banned by Foxite_: bla
```

Which is how it appears in game.

Some investigation has shown that the newlines are entirely missing; there are no characters between `:` and `D`, and `g` and `T`. 

I don't know if this is a problem with Minecraft or with this library, but I'm hoping you could see if it is fixable from this library.

**Comment by Foxite** [comment]
This appears to be a Minecraft problem, other rcon libraries have the same problem. I'm going to see if it can be fixed and post the solution here for any future google users.

**Comment by stefanodriussi** [comment]
Hi @Foxite , thanks for pointing this out 👍
