### ISSUE TITLE
Please add support for different encoding

### ISSUE THREAD

**Issue by CDboyOne** [stefanodriussi/rconsharp#57]
srcds console may response in different encodings. For example, in China locale it uses gb2312 encoding.

**Comment by stefanodriussi** [comment]
I see. Never thought about that. Something configurable would do the trick. I'll think about how to integrate that.

**Comment by CDboyOne** [comment]
Thanks a lot. Are you thinking about auto encoding detection? Actually you can also give the library user a parameter to specify an encoding.

**Comment by stefanodriussi** [comment]
I'd rather go for the parametric option.

**Comment by CDboyOne** [comment]
Excellent! Will you update it on NuGet?
