### ISSUE TITLE
ExecuteCommandAsync doesn't return respond!

### ISSUE THREAD

**Issue by mhmd98** [stefanodriussi/rconsharp#9]
```
class Program
    {
        static void Main(string[] args)
        {
            MainAsync().Wait();
        }

        static async Task MainAsync()
        {
            INetworkSocket socket = new RconSocket();
            RconMessenger messenger = new RconMessenger(socket);
            bool isConnected = await messenger.ConnectAsync("192.168.1.216", 27019); //true
            bool authenticated = await messenger.AuthenticateAsync("Password");
            if (authenticated) //true
            {
                var respond = await messenger.ExecuteCommandAsync("help status");
                Console.WriteLine(respond); //value of respond here = ""
            }

            Console.ReadKey();
        }
    }

```
this will print nothing on the console. while the respond on the server console was:
"status"                                                                         - Display map and connection status.

I tried to use a different library (CoreRcon) and it works (so there is no Rcon problems in the server or it's configuration), but it doesn't properties to check if the connection was successful which i find better than using try catch blocks and using blocks.
so am i doing something wrong or is it a bug in the library itself?

**Comment by stefanodriussi** [comment]
I'll give it a look. Could you please tell me what kind of RCON server are you connecting to ? During my early tests I was targeting a Minecraft server but it was long time ago...

**Comment by mhmd98** [comment]
it's a CSGO Server but there shouldn't be a big difference in the way of sending and receiving the packets i guess the only difference will be in the commands themselves.
Also thank you for your time.

**Comment by stefanodriussi** [comment]
I totally agree with you, RCON is just the transport protocol. I was trying to get as much informations as possible. I'll try to set up a CSGO Server and connect with it.

**Comment by stefanodriussi** [comment]
I've managed to run a hosted CSGO server and verify that the string returned by your example is indeed empty. It looks like it's some buffering related issue on the network stream.
As soon as I find some spare time, I'll port this library to .net Standard 2.0 and get rid of the separate impelemtation. I'll take the chance to also fix a thing or two and improve the library.
If you need an immediate fix, just drop me a message here and i'll provide you a temporary workaround

**Comment by mhmd98** [comment]
Great to hear, i don't need an immediate fix so you can take your time. one other thing i would like you to check while your at it is the possibility of implementing a event for log as it can be used for chat in CSGO i think, i know you had that as a goal in your library (#6 ) so maybe you could do that too while your at it! (if you have time for it ofc)
